# SPRINT 5 - Modelagem

### Objetivo:

Comparar modelos e descobrir qual prevê churn melhor.

Vamos começar com Logistic Regression. Por quê? Porque é baseline clássico de churn.

---

## Etapa 1 - Carregar Dataset Processado

In [77]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/processed/encoded_df.csv')

df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,False,True,False,False,True,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,0,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,1,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,0,True,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,1,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False


---

## Etapa 2 — Conferir dataset

In [78]:
df.shape

(7032, 31)

In [79]:
df.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [80]:
df['Churn'].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

---

## Etapa 3 — Separar Features e Target

In [81]:
#O X representa as variáveis independentes
X = df.drop('Churn', axis=1)

#O Y representa o target (churn)
y = df['Churn']

In [82]:
print(X.shape)
print(y.shape)

(7032, 30)
(7032,)


---

## Etapa 4 — Dividir treino e teste

In [83]:
#Importando biblioteca para treino

from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, # 20% destinado a teste
    random_state=42,
    stratify=y
)

In [85]:
print(X_train.shape)
print(X_test.shape)

(5625, 30)
(1407, 30)


---

## Etapa 5 — Escalonamento

In [86]:
from sklearn.preprocessing import StandardScaler

In [87]:
scaler = StandardScaler()

In [88]:
X_train_scaled = scaler.fit_transform(X_train)

In [89]:
X_test_scaled = scaler.transform(X_test)

---

## Etapa 6 — Logistic Regression

In [90]:
from sklearn.linear_model import LogisticRegression

In [91]:
#Criação do Modelo

model_lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [92]:
#Treinamento

model_lr.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

---

## Etapa 7 — Predição

In [93]:
y_pred_lr = model_lr.predict(X_test_scaled)

---

## Etapa 8 — Avaliação do modelo

In [94]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score
)


In [95]:
#Acurácia

accuracy = accuracy_score(y_test, y_pred_lr) * 100

print(f'Accuracy: {accuracy:.2f}%')

Accuracy: 80.38%


In [96]:
#F1-Score

score = f1_score(y_test, y_pred_lr) * 100
print(f'F1 Score: {score:.2f}%')

F1 Score: 60.91%


In [97]:
#Classification Report

print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.57      0.61       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.80      0.80      1407



In [98]:
#Matriz de Confusão

confusion_matrix(y_test, y_pred_lr)

array([[916, 117],
       [159, 215]])

---

## Conclusão do Modelo de Regressão Logística

A Regressão Logística apresentou desempenho inicial satisfatório como baseline, alcançando aproximadamente 80% de accuracy. No entanto, observou-se recall de 57% para a classe churn, indicando oportunidade de melhoria na capacidade do modelo em identificar clientes propensos ao cancelamento. Como o custo de falsos negativos é alto nesse problema de negócio, modelos adicionais serão comparados visando aumentar o recall

---

# Sprint 5.2 - Testando novos modelos

---

## Modelo 1 - Decision Tree (Árvore de Decisão)

In [99]:
#Importar
from sklearn.tree import DecisionTreeClassifier

In [100]:
#Criar o Modelo

model_dt = DecisionTreeClassifier(
    random_state=42,
    max_depth=5 # usado para não ocorrer overfitting
)

In [101]:
#Treinar Modelo

model_dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [102]:
#Predição

y_pred_dt = model_dt.predict(X_test)

In [103]:
#Avaliação

print('Accuracy:',
      accuracy_score(y_test, y_pred_dt))

print(classification_report(
    y_test,
    y_pred_dt
))
print("Matriz de Confusão")
print(confusion_matrix(
    y_test,
    y_pred_dt
))

Accuracy: 0.7782515991471215
              precision    recall  f1-score   support

           0       0.85      0.84      0.85      1033
           1       0.58      0.60      0.59       374

    accuracy                           0.78      1407
   macro avg       0.72      0.72      0.72      1407
weighted avg       0.78      0.78      0.78      1407

Matriz de Confusão
[[872 161]
 [151 223]]


---

## Modelo 2 - Random Forest

In [104]:
#Importar lib

from sklearn.ensemble import RandomForestClassifier

In [105]:
#Criar Modelo

model_rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    max_depth=8
)

# Com 200 árvores para mais robustez e max_depth=8 para controlar o overfitting

In [106]:
#Treinar

model_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, n_estimators=200, random_state=42)

In [107]:
#Predição

y_pred_rf = model_rf.predict(X_test)

In [108]:
#Avaliação

print('Accuracy:',
      accuracy_score(y_test, y_pred_rf))

print(classification_report(
    y_test,
    y_pred_rf
))
print("Matriz de Confusão")
print(confusion_matrix(
    y_test,
    y_pred_rf
))

Accuracy: 0.7910447761194029
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1033
           1       0.64      0.48      0.55       374

    accuracy                           0.79      1407
   macro avg       0.74      0.69      0.71      1407
weighted avg       0.78      0.79      0.78      1407

Matriz de Confusão
[[934  99]
 [195 179]]


---

Embora a Logistic Regression tenha apresentado melhor equilíbrio geral entre precisão e F1-score, em um cenário real de churn eu priorizaria recall, pois o custo de falsos negativos é elevado — clientes podem cancelar sem que a empresa tenha oportunidade de agir preventivamente

---

# Sprint 5.3 - Threshold Tuning

---

## Etapa 1 - Obter probabilidades

In [128]:
y_prob_lr = model_lr.predict_proba(X_test_scaled)[:, 1]

y_prob_lr

array([0.01711495, 0.59613179, 0.00476432, ..., 0.1307601 , 0.02479905,
       0.00438623])

---

## Etapa 2 — Testar thresholds

In [110]:
#Importar a lib

from sklearn.metrics import classification_report

In [114]:
#testar com 0.50

threshold = 0.50

y_pred_custom = (
    y_prob_lr >= threshold
).astype(int)

print(classification_report(
    y_test,
    y_pred_custom
))

print(confusion_matrix(
    y_test,
    y_pred_custom
))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.57      0.61       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.80      0.80      1407

[[916 117]
 [159 215]]


In [111]:
#testar com 0.40

threshold = 0.40

y_pred_custom = (
    y_prob_lr >= threshold
).astype(int)

print(classification_report(
    y_test,
    y_pred_custom
))

print(confusion_matrix(
    y_test,
    y_pred_custom
))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85      1033
           1       0.58      0.68      0.63       374

    accuracy                           0.78      1407
   macro avg       0.73      0.75      0.74      1407
weighted avg       0.80      0.78      0.79      1407

[[846 187]
 [118 256]]


In [112]:
#testar com 0.35

threshold = 0.35

y_pred_custom = (
    y_prob_lr >= threshold
).astype(int)

print(classification_report(
    y_test,
    y_pred_custom
))

print(confusion_matrix(
    y_test,
    y_pred_custom
))

              precision    recall  f1-score   support

           0       0.88      0.78      0.83      1033
           1       0.54      0.72      0.62       374

    accuracy                           0.77      1407
   macro avg       0.71      0.75      0.73      1407
weighted avg       0.79      0.77      0.77      1407

[[808 225]
 [105 269]]


In [113]:
#Testar com 0.30

threshold = 0.30

y_pred_custom = (
    y_prob_lr >= threshold
).astype(int)

print(classification_report(
    y_test,
    y_pred_custom
))

print(confusion_matrix(
    y_test,
    y_pred_custom
))

              precision    recall  f1-score   support

           0       0.89      0.74      0.81      1033
           1       0.51      0.76      0.61       374

    accuracy                           0.74      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.79      0.74      0.76      1407

[[762 271]
 [ 90 284]]


---

| Threshold | Precision | Recall | F1 |
| --------- | --------: | -----: | -: |
| 0.50      |      0.65 |   0.57 |0.61|
| 0.40      |      0.58 |   0.68 |0.63|
| 0.35      |      0.54 |   0.72 |0.62|
| 0.30      |      0.51 |   0.76 |0.61|

Foram avaliados diferentes thresholds de decisão para otimizar a identificação de clientes com risco de churn. O threshold padrão (0.50) apresentou recall limitado. Após ajuste, o threshold 0.40 demonstrou melhor equilíbrio entre precisão e capacidade preditiva, elevando o recall de 57% para 68% sem perda excessiva de precisão.


---

## Salvar Modelo

In [130]:
import joblib

In [133]:
#Salvar Modelo

joblib.dump(
    model_lr,
    '../models/model_lr.pkl'
)

['../models/model_lr.pkl']

In [134]:
#Salvar Scaler

joblib.dump(
    scaler,
    '../models/scaler.pkl'
)

['../models/scaler.pkl']

In [136]:
#Salvar features

feature_names = X.columns

joblib.dump(
    feature_names,
    '../models/feature_names.pkl'
)

['../models/feature_names.pkl']